// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication2.Data;

namespace WebApplication2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190206121646_seed2")]
    partial class seed2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication2.Tables.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("UserName");

                    b.HasKey("CustomerID");

                    b.ToTable("Customer","Service");

                    b.HasData(
                        new
                        {
                            CustomerID = 1,
                            Email = "asd@asd.asd",
                            FirstName = "asd",
                            LastName = "asd",
                            Password = "asdasd",
                            PhoneNumber = "123456789",
                            UserName = "asd"
                        },
                        new
                        {
                            CustomerID = 2,
                            Email = "asdf@asd.asd",
                            FirstName = "asdf",
                            LastName = "asdf",
                            Password = "asdasdasd",
                            PhoneNumber = "123456789",
                            UserName = "asdf"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
